### ISSUE TITLE
npm start end with error

### ISSUE THREAD

**Issue by elmor34** [webmaxru/ngIO16#1]
I started with :

```
npm install
npm start

```

Then I got the following error with no output on browser

When I added missing angularmaterial. card with  **"@angular2-material/card": "^2.0.0-alpha.4",**

I got : **@angular2-material/card@2.0.0-alpha.4 
`-- UNMET PEER DEPENDENCY angular2@^2.0.0-beta.8**

```
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
Livereload server on http://localhost:49152
Serving on http://localhost:4200/
The Broccoli Plugin: [BroccoliTypeScriptCompiler] failed with:
Error: Typescript found the following errors:
  /Users/gokhanaykan/Sites/ngIO16-master/tmp/broccoli_type_script_compiler-input_base_path-Hok0KGBD.tmp/0/src/app/hello-mobile.component.ts (8, 36): Cannot find module '@angular2-material/card'.
    at BroccoliTypeScriptCompiler._doIncrementalBuild (/Users/gokhanaykan/Sites/ngIO16-master/node_modules/angular-cli/lib/broccoli/broccoli-typescript.js:115:19)
    at BroccoliTypeScriptCompiler.build (/Users/gokhanaykan/Sites/ngIO16-master/node_modules/angular-cli/lib/broccoli/broccoli-typescript.js:43:10)
    at /Users/gokhanaykan/Sites/ngIO16-master/node_modules/broccoli-caching-writer/index.js:152:21
    at lib$rsvp$$internal$$tryCatch (/Users/gokhanaykan/Sites/ngIO16-master/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/gokhanaykan/Sites/ngIO16-master/node_modules/rsvp/dist/rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (/Users/gokhanaykan/Sites/ngIO16-master/node_modules/rsvp/dist/rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (/Users/gokhanaykan/Sites/ngIO16-master/node_modules/rsvp/dist/rsvp.js:1198:9)
    at nextTickCallbackWith0Args (node.js:453:9)
    at process._tickCallback (node.js:382:13)
```

**Comment by webmaxru** [comment]
Thank you for reporting! I've fixed the dependencies + wrote short instructions on how to run it
